### ISSUE TITLE
Does not support streaming output for long running command

### ISSUE THREAD

**Issue by dtangster** [rubencaro/sshex#1]
I haven't tested it, but I don't think the current implementation supports streaming output for a long running command based on reading the code. I'm still new to Elixir, but it would be neat if that was supported. I was planning in the near future to try and implement a browser client that shows terminal output in real time.

**Comment by rubencaro** [comment]
You are right. It doesn't. But I think it's a good idea! 

Right now it simply holds the entire output until it's complete, and then returns it one piece.

To do what you suggest you may need to stream the response as it comes, not holding it on memory. Maybe implementing some kind of [Stream](http://elixir-lang.org/docs/stable/elixir/Stream.html). I think it's totally doable.

I would stream the data (if any) right before the recursion [here](https://github.com/rubencaro/sshex/blob/master/lib/sshex.ex#L74) and always pass and empty string as `data` to the next iteration [here](https://github.com/rubencaro/sshex/blob/master/lib/sshex.ex#L76). The rest may be the same.

What do you think? 

A Pull Request is always welcome!

**Comment by dtangster** [comment]
Sounds interesting, but I am still new to all this Elixir stuff and the functional paradigm. Maybe I'll take a stab at it when I have time on the weekend.

**Comment by rubencaro** [comment]
I'm working on it now, on branch `stream`.

**Comment by rubencaro** [comment]
I just released [1.3](https://hex.pm/packages/sshex) with support for streaming, See [docs](https://github.com/rubencaro/sshex#streaming).
