### ISSUE TITLE
Status seems to be not consistent

### ISSUE THREAD

**Issue by iamajvillalobos** [rubencaro/sshex#11]
I'm using this on a small script I have in checking all my vps. 

```
response = SSHEx.connect ip: domain, user: 'user' , password: 'password'

    case response do
      {:ok, _conn} -> %{name: domain, status: "online"}
      {:error, _conn} -> %{name: domain, status: "offline"}
    end
```

I use the snippet above for my function, sometimes it reports that the vps is down, but when I ssh into it, it's online. Is there other options I need to add for consistency?

**Comment by rubencaro** [comment]
It looks like something related to the underlying networking/SSH negotiation. 

Check for any `sshguard/fail2ban` activity on your servers, or the continuity of the network connection, or the config of your `sshd` daemon (you may be limiting the number of connections). 

You can take a look at the failing reason for more info, like this:
```elixir
response = SSHEx.connect ip: domain, user: 'user' , password: 'password'
case response do
  {:ok, _conn} -> %{name: domain, status: "online"}
  {:error, reason} -> %{name: domain, status: "offline", reason: reason}
end
```
These come straight from Erlang's `ssh`, so you may need to go there to be able to know more details on the actual reasons given.

Thanks.
