### ISSUE TITLE
Password prompt in clear text

### ISSUE THREAD

**Issue by cmcraft** [rubencaro/sshex#18]
Not an issue per-se but a format nitpick. Currently the password prompt is in clear text. I understand that if we use ssh keys we bypass this issue, but on systems where that isn't an option, this becomes a security issue.

**Comment by rubencaro** [comment]
@cmcraft ok. What is your proposal?

**Comment by cmcraft** [comment]
@rubencaro That we obfuscate/drop the typed prompt so passwords don't show up when they are entered into the iex session.

**Comment by rubencaro** [comment]
@cmcraft how would you do that exactly. Can you elaborate?

**Comment by cmcraft** [comment]
@rubencaro I will attempt to draft up a solution tonight.

**Comment by cmcraft** [comment]
Seeing as how everything I've read on Erlang's ssh system denotes using an ssh key pair by default, I would like to apologize for this useless issue request.  I assume that the consensus is that 'if you're going to be dumb and use passwords, we're not going to make you feel better about it'. So I will revise accordingly for any projects I create. Again, I'm sorry for the annoyance.

**Comment by rubencaro** [comment]
@cmcraft not at all! Don't be sorry for exposing your ideas. Good ones are to be followed, not so good ones are to be discarded. All of them are welcome.

Thanks!
