### ISSUE TITLE
no timeout available

### ISSUE THREAD

**Issue by vans163** [rubencaro/sshex#20]
If you do a SSHEx.cmd!(self(), "ls"), it will never time out, even though the default is 5000 ms.  It should time out in this case I think.

**Comment by rubencaro** [comment]
I suspect it has to be with the `self()` part. That should be a connection returned by `SSHEx.connect/1`.

The call sequence goes like this:
* Run `SSHEx.cmd!(self(), "ls")`
* [Call run/3](https://github.com/rubencaro/sshex/blob/5a15d94f253e3c3ec3abe7802755a2300fee1413/lib/sshex.ex#L97)
* [Call open_channel_and_exec/3](https://github.com/rubencaro/sshex/blob/5a15d94f253e3c3ec3abe7802755a2300fee1413/lib/sshex.ex#L72)
* [Call open_channel/3](https://github.com/rubencaro/sshex/blob/5a15d94f253e3c3ec3abe7802755a2300fee1413/lib/sshex.ex#L183)
* [Call :ssh_connection.session_channel/2](https://github.com/rubencaro/sshex/blob/5a15d94f253e3c3ec3abe7802755a2300fee1413/lib/sshex.ex#L192)

In the end it is up to [:ssh_connection.session_channel/2](http://erlang.org/doc/man/ssh_connection.html#session_channel-2) to decide what to do on your case.

**Comment by vans163** [comment]
Yea I mean that there should be a timeout as there is a race condition here.  If connection returned by SSHEx.connect/1 is already processing, but we have its pid and call it from a different process, the caller will block forever.

Passing self() was just a lazy way to demonstrate this.

**Comment by rubencaro** [comment]
I guess that's just the behaviour of Erlang's `:ssh` library. As you can see in the code I pointed you, `SSHEx` is passing every timeout you configure down to `:ssh` and friends.

If you see a way of solving your problem by using directly `:ssh`, then maybe we can add it to `SSHEx`.
