### ISSUE TITLE
How can I use a certificate with it?

### ISSUE THREAD

**Issue by GildedHonour** [rubencaro/sshex#9]
How can I use a certificate with it?

**Comment by rubencaro** [comment]
Do you mean [this](https://github.com/rubencaro/sshex#alternative-keys)?

As SSHEx is merely a front end to erlang's ssh, it should be merely a problem of passing the right options to the underlying ssh application. If you find how to do what you want with erlang's ssh, then let me know and I guess I can find the way to make SSHEx let you do it too.

**Comment by rubencaro** [comment]
@GildedHonour closing this. Feel free to reopen if you cannot find the way to map your Erlang's ssh use to a SSHEx call.
